[server]
enableStaticServing = true

[theme]
base = "dark"
primaryColor = "#829cff"
backgroundColor = "#08090b"
secondaryBackgroundColor = "#14161c"
textColor = "#e3e7ef"
font = "sans serif"

[browser]
gatherUsageStats = false
